import { Router } from 'express';
import * as adminController from './admin.controller';
import { authenticate } from '../../middleware/auth.middleware';
import { authorize, authorizeSuperAdmin, authorizeAdminTab } from '../../middleware/rbac.middleware';
import { uploadBlogImage, uploadJobImage } from '../../middleware/upload.middleware';

const router = Router();

router.post('/login', adminController.login);
router.get('/sub-admins', authenticate, authorizeSuperAdmin, adminController.getSubAdmins);
router.post('/sub-admins', authenticate, authorizeSuperAdmin, adminController.createSubAdmin);
router.put('/sub-admins/:id/password', authenticate, authorizeSuperAdmin, adminController.updateSubAdminPassword);
router.put('/sub-admins/:id/permissions', authenticate, authorizeSuperAdmin, adminController.updateSubAdminPermissions);
router.delete('/sub-admins/:id', authenticate, authorizeSuperAdmin, adminController.deleteSubAdmin);
router.get('/talents', authenticate, authorize('ADMIN'), authorizeAdminTab('talents'), adminController.getTalents);
router.get('/companies', authenticate, authorize('ADMIN'), authorizeAdminTab('companies'), adminController.getCompanies);
router.get('/companies/active', authenticate, authorize('ADMIN'), authorizeAdminTab('jobs'), adminController.getActiveCompanies);
router.post('/jobs', authenticate, authorize('ADMIN'), authorizeAdminTab('jobs'), adminController.adminCreateJob);
router.post('/jobs/:id/roles', authenticate, authorize('ADMIN'), authorizeAdminTab('jobs'), adminController.adminAddRole);
router.patch('/companies/:id/verify', authenticate, authorize('ADMIN'), authorizeAdminTab('companies'), adminController.updateCompanyVerify);
router.patch('/companies/:id/status', authenticate, authorize('ADMIN'), authorizeAdminTab('companies'), adminController.updateCompanyStatus);
router.post('/companies/:id/login', authenticate, authorize('ADMIN'), authorizeAdminTab('companies'), adminController.loginAsRecruiter);
router.get('/jobs', authenticate, authorize('ADMIN'), authorizeAdminTab('jobs'), adminController.getJobs);
router.get('/jobs/:id/payment', authenticate, authorize('ADMIN'), authorizeAdminTab('jobs'), adminController.getJobPaymentDetails);
router.get('/jobs/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('jobs'), adminController.getAdminJobById);
router.put('/jobs/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('jobs'), adminController.adminUpdateJob);
router.put('/jobs/:jobId/roles/:roleId', authenticate, authorize('ADMIN'), authorizeAdminTab('jobs'), adminController.adminUpdateRole);
router.patch('/jobs/:id/status', authenticate, authorize('ADMIN'), authorizeAdminTab('jobs'), adminController.updateJobStatus);
router.patch('/talents/:id/status', authenticate, authorize('ADMIN'), authorizeAdminTab('talents'), adminController.updateTalentStatus);
router.post('/companies/:id/toggle-internal', authenticate, authorize('ADMIN'), authorizeAdminTab('companies'), adminController.toggleInternalCompany);
router.get('/talents/:id/subscription', authenticate, authorize('ADMIN'), authorizeAdminTab('talents'), adminController.getTalentSubscriptionDetails);
router.put('/talents/:id/subscription', authenticate, authorize('ADMIN'), authorizeAdminTab('talents'), adminController.updateTalentSubscription);
router.post('/talents/:id/login', authenticate, authorize('ADMIN'), authorizeAdminTab('talents'), adminController.loginAsTalent);
router.get('/blogs', authenticate, authorize('ADMIN'), authorizeAdminTab('work'), adminController.getAdminBlogs);
router.post('/blogs', authenticate, authorize('ADMIN'), authorizeAdminTab('work'), adminController.createBlog);
router.put('/blogs/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('work'), adminController.updateBlog);
router.post('/blogs/image', authenticate, authorize('ADMIN'), authorizeAdminTab('work'), uploadBlogImage, adminController.uploadBlogImageHandler);
router.post('/jobs/image', authenticate, authorize('ADMIN'), authorizeAdminTab('jobs'), uploadJobImage, adminController.uploadJobImageHandler);
router.delete('/blogs/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('work'), adminController.deleteBlog);
router.get('/languages', authenticate, authorize('ADMIN'), authorizeAdminTab('language'), adminController.getLanguages);
router.post('/languages', authenticate, authorize('ADMIN'), authorizeAdminTab('language'), adminController.createLanguage);
router.put('/languages/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('language'), adminController.updateLanguage);
router.delete('/languages/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('language'), adminController.deleteLanguage);
router.get('/nationalities', authenticate, authorize('ADMIN'), authorizeAdminTab('nationality'), adminController.getNationalities);
router.post('/nationalities', authenticate, authorize('ADMIN'), authorizeAdminTab('nationality'), adminController.createNationality);
router.put('/nationalities/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('nationality'), adminController.updateNationality);
router.delete('/nationalities/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('nationality'), adminController.deleteNationality);
router.get('/ethnicities', authenticate, authorize('ADMIN'), authorizeAdminTab('ethnicity'), adminController.getEthnicities);
router.post('/ethnicities', authenticate, authorize('ADMIN'), authorizeAdminTab('ethnicity'), adminController.createEthnicity);
router.put('/ethnicities/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('ethnicity'), adminController.updateEthnicity);
router.delete('/ethnicities/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('ethnicity'), adminController.deleteEthnicity);
router.get('/categories', authenticate, authorize('ADMIN'), authorizeAdminTab('category'), adminController.getCategories);
router.post('/categories', authenticate, authorize('ADMIN'), authorizeAdminTab('category'), adminController.createCategory);
router.put('/categories/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('category'), adminController.updateCategory);
router.delete('/categories/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('category'), adminController.deleteCategory);
router.get('/cities', authenticate, authorize('ADMIN'), authorizeAdminTab('city'), adminController.getCities);
router.get('/countries/all', authenticate, authorize('ADMIN'), authorizeAdminTab('city'), adminController.getAllCountries);
router.post('/cities', authenticate, authorize('ADMIN'), authorizeAdminTab('city'), adminController.createCity);
router.put('/cities/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('city'), adminController.updateCity);
router.delete('/cities/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('city'), adminController.deleteCity);
router.get('/countries', authenticate, authorize('ADMIN'), authorizeAdminTab('country'), adminController.getCountries);
router.post('/countries', authenticate, authorize('ADMIN'), authorizeAdminTab('country'), adminController.createCountry);
router.put('/countries/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('country'), adminController.updateCountry);
router.delete('/countries/:id', authenticate, authorize('ADMIN'), authorizeAdminTab('country'), adminController.deleteCountry);
router.get('/email-templates', authenticate, authorize('ADMIN'), authorizeAdminTab('templates'), adminController.getEmailTemplates);
router.get('/email-templates/:key', authenticate, authorize('ADMIN'), authorizeAdminTab('templates'), adminController.getEmailTemplateByKey);
router.put('/email-templates/:key', authenticate, authorize('ADMIN'), authorizeAdminTab('templates'), adminController.updateEmailTemplate);
router.get('/cms', authenticate, authorize('ADMIN'), authorizeAdminTab('cms'), adminController.getCmsPages);
router.get('/cms/:key', authenticate, authorize('ADMIN'), authorizeAdminTab('cms'), adminController.getCmsPageByKey);
router.post('/cms', authenticate, authorize('ADMIN'), authorizeAdminTab('cms'), adminController.createCmsPage);
router.put('/cms/:key', authenticate, authorize('ADMIN'), authorizeAdminTab('cms'), adminController.updateCmsPage);
router.delete('/cms/:key', authenticate, authorize('ADMIN'), authorizeAdminTab('cms'), adminController.deleteCmsPage);

export default router;
